# Generated by Django 5.0.2 on 2024-02-23 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='ФИО сотрудника')),
                ('job_title', models.CharField(max_length=50, verbose_name='Должность')),
                ('in_company', models.DateTimeField(verbose_name='Дата приема на работу')),
            ],
        ),
    ]
