# Generated by Django 5.0.2 on 2024-02-28 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employees',
            options={'verbose_name': 'Пользователь сервиса', 'verbose_name_plural': 'Пользователи сервиса'},
        ),
    ]
