# Generated by Django 5.0.2 on 2024-03-24 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service_company',
            name='phone',
            field=models.CharField(default='', max_length=12, verbose_name='Номер телефона аварийной бригады'),
        ),
        migrations.AddField(
            model_name='service_company',
            name='title',
            field=models.TextField(default='', max_length=500, verbose_name='Деятельность компании'),
        ),
        migrations.AlterField(
            model_name='service_company',
            name='quality_of_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='systems.quality_of_service', verbose_name='Качество обслуживания от 1 до 5'),
        ),
    ]
