# Generated by Django 4.2.6 on 2023-10-25 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quality_of_service',
            name='quality',
            field=models.CharField(verbose_name='Качество обслуживания'),
        ),
    ]
