# Generated by Django 4.2.6 on 2023-10-25 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0002_alter_quality_of_service_quality'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50, verbose_name='Город')),
                ('settlement', models.CharField(max_length=50, verbose_name='Поселение')),
                ('street', models.CharField(max_length=50, verbose_name='Улица')),
                ('home', models.CharField(max_length=50, verbose_name='Дом')),
                ('corps', models.CharField(max_length=50, verbose_name='Корпус')),
            ],
            options={
                'verbose_name': 'Адрес',
                'verbose_name_plural': 'Адреса',
            },
        ),
    ]
