# Generated by Django 5.0.2 on 2024-03-24 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0002_service_company_phone_service_company_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service_company',
            name='image',
            field=models.ImageField(default='изображение любого формата', null=True, upload_to='service_company/', verbose_name='Изображение'),
        ),
    ]
