# Generated by Django 5.0.2 on 2024-03-24 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0003_service_company_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название юридического лица')),
            ],
            options={
                'verbose_name': 'Компания',
                'verbose_name_plural': 'Компании',
            },
        ),
        migrations.AddField(
            model_name='equipment',
            name='location',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='systems.location', verbose_name='Локация'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='passport_number',
            field=models.IntegerField(null=True, verbose_name='Номер в паспорте (при наличии)'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='company',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='systems.company', verbose_name='Юридическое лицо'),
        ),
    ]
