# Generated by Django 4.2.6 on 2023-10-25 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0004_alter_address_city_alter_address_corps_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='address',
            name='corps',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Корпус'),
        ),
        migrations.AlterField(
            model_name='address',
            name='home',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Дом'),
        ),
        migrations.AlterField(
            model_name='address',
            name='settlement',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Поселение'),
        ),
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Улица'),
        ),
    ]
