# Generated by Django 5.0.2 on 2024-03-24 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0004_company_equipment_location_equipment_passport_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='passport_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Номер в паспорте (при наличии)'),
        ),
    ]
