# Generated by Django 5.0.2 on 2024-03-24 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0005_alter_equipment_passport_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='corps',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Корпус'),
        ),
    ]
