# Generated by Django 5.0.2 on 2024-03-24 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0006_alter_address_corps'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='corps',
        ),
    ]
