# Generated by Django 5.0.2 on 2024-04-03 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0007_remove_address_corps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quality_of_service',
            name='quality',
            field=models.CharField(max_length=10, verbose_name='Качество обслуживания'),
        ),
    ]
