# Generated by Django 5.0.2 on 2024-04-07 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0008_alter_quality_of_service_quality'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='quantity',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество'),
        ),
    ]
