# Generated by Django 5.0 on 2024-01-10 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0009_remove_systems_number_equipment_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='systems',
            name='title',
            field=models.TextField(default='', max_length=500, verbose_name='Описание'),
        ),
    ]
