# Generated by Django 5.0.2 on 2024-04-15 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0010_alter_equipment_passport_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='systems',
            name='url',
            field=models.URLField(default='', verbose_name='Ссылка'),
        ),
    ]
