# Generated by Django 5.0.1 on 2024-01-24 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0011_tasks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='datetime',
            field=models.DateTimeField(verbose_name='Выполнить до'),
        ),
    ]
