# Generated by Django 5.0.2 on 2024-04-16 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0012_equipment_cat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='systems',
            name='cat_id',
            field=models.IntegerField(default='1', verbose_name='Категория'),
        ),
    ]
