# Generated by Django 5.0.1 on 2024-01-28 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0012_alter_tasks_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='address',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='systems.address', verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='systems.systems', verbose_name='Выберите систему'),
        ),
    ]
