# Generated by Django 5.0.2 on 2024-04-21 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0015_select_urgency_tasks_urgency_task'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='select_urgency',
            options={'verbose_name': 'Срочность', 'verbose_name_plural': 'Срочность'},
        ),
    ]
