# Generated by Django 4.2.6 on 2023-10-25 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('systems', '0005_alter_address_city_alter_address_corps_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_condition', models.CharField(max_length=10, verbose_name='Статус проишествия')),
            ],
            options={
                'verbose_name': 'Статус',
                'verbose_name_plural': 'Статус',
            },
        ),
        migrations.CreateModel(
            name='Types_incidents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100, verbose_name='Тип проишествия')),
            ],
            options={
                'verbose_name': 'Тип проишествия',
                'verbose_name_plural': 'Тип проишествия',
            },
        ),
        migrations.CreateModel(
            name='Incidents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Дата проишествия')),
                ('title', models.TextField(max_length=1000, verbose_name='Описание проишествия')),
                ('incident_analysis', models.TextField(max_length=1000, verbose_name='Описание проишествия')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='systems.address', verbose_name='Выберите адрес')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='systems.equipment', verbose_name='Выберите оборудование')),
                ('status_condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum_incidents.status', verbose_name='Выберите статус')),
                ('types_incidents', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum_incidents.types_incidents', verbose_name='Тип проишествия')),
            ],
            options={
                'verbose_name': 'Проишествие',
                'verbose_name_plural': 'Проишествия',
            },
        ),
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_of_discussion', models.CharField(max_length=100, verbose_name='Тема обсуждения')),
                ('name', models.CharField(max_length=50, verbose_name='ФИО')),
                ('email_user', models.EmailField(max_length=50, verbose_name='Электронная почта')),
                ('text_of_discussion', models.TextField(verbose_name='Введите текст для обсуждения')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='systems.equipment', verbose_name='Выберите оборудование')),
            ],
            options={
                'verbose_name': 'Тема для обсуждения',
                'verbose_name_plural': 'Темы для обсуждения',
            },
        ),
    ]
