# Generated by Django 5.0.2 on 2024-04-09 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0001_initial'),
        ('purchase_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchase',
            options={'verbose_name': 'Закупка', 'verbose_name_plural': 'Закупки'},
        ),
        migrations.AlterModelOptions(
            name='status_purchase',
            options={'verbose_name': 'Статус закупки', 'verbose_name_plural': 'Статус закупки'},
        ),
        migrations.AddField(
            model_name='purchase',
            name='incident',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='incidents.incidents', verbose_name='Выберите проишествие в системе s.engineer'),
        ),
    ]
