# Generated by Django 5.0.2 on 2024-04-14 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0001_initial'),
        ('purchase_app', '0002_alter_purchase_options_alter_status_purchase_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='incident',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='incidents.incidents', verbose_name='Выберите проишествие в системе s.engineer'),
        ),
    ]
