# Generated by Django 5.0.2 on 2024-04-15 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_app', '0003_alter_purchase_incident'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='price',
            field=models.IntegerField(max_length=50, verbose_name='Цена, в рублях'),
        ),
    ]
