# Generated by Django 5.0.2 on 2024-04-16 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_app', '0004_alter_purchase_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='price',
            field=models.IntegerField(verbose_name='Цена, в рублях'),
        ),
    ]
