# Generated by Django 5.0.2 on 2024-04-17 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0004_alter_defect_elimination_period'),
        ('purchase_app', '0005_alter_purchase_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='defect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='incidents.defect', verbose_name='Выберите дефект из списка'),
        ),
    ]
