# Generated by Django 5.0.2 on 2024-04-17 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0001_initial'),
        ('systems', '0014_systems_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Defect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cause', models.CharField(max_length=100, verbose_name='Причина')),
                ('elimination_period', models.IntegerField(verbose_name='Срок устранения')),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='systems.address', verbose_name='Выберите адрес')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='systems.location', verbose_name='Выберите локацию')),
                ('service_company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='systems.service_company', verbose_name='Компания, выполняющая работу')),
                ('system', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='systems.systems', verbose_name='Выберите систему')),
            ],
            options={
                'verbose_name': 'Проишествие',
                'verbose_name_plural': 'Проишествия',
            },
        ),
    ]
