# Generated by Django 5.0.2 on 2024-04-17 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0003_alter_defect_options_defect_equipment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defect',
            name='elimination_period',
            field=models.IntegerField(verbose_name='Срок устранения, в днях'),
        ),
    ]
