# Generated by Django 5.0.2 on 2024-04-17 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0002_maintenance_url'),
        ('systems', '0014_systems_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50, verbose_name='Статус ТО')),
            ],
            options={
                'verbose_name': 'Статус ТО',
                'verbose_name_plural': 'Статусы ТО',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(verbose_name='Выберите дату проведения ТО')),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='systems.address', verbose_name='Выберите адрес')),
                ('equipments', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='systems.equipment', verbose_name='Выберите оборудование')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='systems.location', verbose_name='Выберите локацию')),
                ('maintenance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='service_app.maintenance', verbose_name='Выберите вид ТО')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='service_app.status', verbose_name='Выберите статус')),
            ],
            options={
                'verbose_name': 'Назначение ТО',
                'verbose_name_plural': 'Назначение ТО',
            },
        ),
    ]
