# Generated by Django 5.0.2 on 2024-02-28 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название статьи')),
                ('text', models.TextField(max_length=5000, verbose_name='Текст статьи')),
                ('added', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время добавления')),
            ],
        ),
        migrations.AlterModelOptions(
            name='document',
            options={'verbose_name': 'Документы', 'verbose_name_plural': 'Документы'},
        ),
    ]
