# Generated by Django 5.0.2 on 2024-02-28 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentation', '0002_addarticle_alter_document_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addarticle',
            options={'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
    ]
