# Generated by Django 5.0.2 on 2024-02-28 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentation', '0003_alter_addarticle_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='addarticle',
            name='image',
            field=models.ImageField(default='изображение любого формата', upload_to='article/', verbose_name='Изображение'),
        ),
    ]
