# Generated by Django 5.0.2 on 2024-04-21 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentation', '0005_remove_addarticle_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='addarticle',
            name='image',
            field=models.ImageField(default='изображение любого формата', upload_to='article/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='addarticle',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='addarticle',
            name='text',
            field=models.TextField(max_length=5000, verbose_name='Текст'),
        ),
    ]
