# Generated by Django 5.0.2 on 2024-04-21 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentation', '0006_addarticle_image_alter_addarticle_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='addarticle',
            name='type_article',
            field=models.CharField(default='', max_length=50, verbose_name='Тип'),
        ),
    ]
