# Generated by Django 5.0.2 on 2024-04-25 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentation', '0007_addarticle_type_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='addarticle',
            name='url',
            field=models.SlugField(default='', max_length=150, unique=True),
        ),
    ]
