# Generated by Django 5.0.2 on 2024-04-25 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentation', '0008_addarticle_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addarticle',
            name='url',
            field=models.SlugField(max_length=150, unique=True),
        ),
    ]
