# Generated by Django 5.0.2 on 2024-04-25 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentation', '0013_remove_addarticle_url_addarticle_url_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addarticle',
            name='url_article',
            field=models.SlugField(default='', max_length=150, unique=True),
        ),
    ]
