# Generated by Django 5.0.2 on 2024-04-25 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentation', '0014_alter_addarticle_url_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='addarticle',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Публикация'),
        ),
        migrations.AlterField(
            model_name='addarticle',
            name='url_article',
            field=models.SlugField(default='', max_length=150, unique=True, verbose_name='Слаг'),
        ),
    ]
